$ANSIBLE_VAULT;1.1;AES256
63383466313034306162643731393738643834326333353564343062373661386433616462653232
3536643165363537666266616139336233396432356262320a626366306530623734643331613361
32363766613630643639353634613535316666653230366563643838646234336234636532623662
6134333366353330630a303338346263386332343239303832326465346466306261333065653166
62636631363039333266353332326539343338363661363463303862366539666261666364383739
32313438656163323630613866643836623761326666363136316163623261393661373066633935
64313430353062636238363538376331343931626638353339333761643733623730313137313334
33323330343133623565656361636136386564363131353436323062333433363666613737363337
39613438353137323635343163336530343361373661363933636261626431346134623636343363
38346336636333613161313362396232633531343661646531643130646238613432366538373764
64396163363161373661613034356138323065333362323636313061303561363934623339613261
37646637336438633063646361333561313731613239303430363132333632373439323036623233
3638
