$ANSIBLE_VAULT;1.1;AES256
62363635323830316166326463366566323537356633613630623235643762313166326337383235
3662386133643965383233663537626530663631393063300a346661626139663138623030316564
35386434653735336364303530306666313734393338343834306566346263303564316530656336
3833393737623765330a613365383765313631616338363331346665383234366238663538343537
31336339386564323766303033616434376266383936333938646438386635643065613263663030
37373238323033366364633766303930373138396265333863313837373962643733356465376130
39663261336565633962393462316265323035353663653532643830376139316333393362623162
62353935333134363532373766653936643435313732363865393661663362623230313430613832
64613664343538376563643837323738626636366139373265633732336165643862653961353230
30356366623832323532653364363632363133383030636439306439643364643930613864616261
31373464653166343932376239303966366165636335333562323739303036613035656465346666
38393839623866393263613761653463326634613361653336636435636166633361623663323139
3661
